default_window_width = 600
min_content_height = 400
max_content_height = 400
name_match_highlight_color = "#e0af68"
decorate_window = false
close_window_on_losing_focus = true
query_placeholder = "Search for applications"
icon_size = 32
toggle_key = "<Super>Shift_L"
min_score = 5
result_size = 10
